const http = require('http');
const fs = require('fs');
const path = require('path');
const url = require('url');
const nodemailer = require('nodemailer');
const cron = require('node-cron');
require('dotenv').config();

const PORT = process.env.PORT || 3000;
const DATA_FILE = path.join(__dirname, 'data.json');

// SMTP Configuration
const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.hostinger.com',
    port: parseInt(process.env.SMTP_PORT) || 465,
    secure: true, // SSL
    auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
    }
});

// Function to send daily email
async function sendDailyReport() {
    try {
        if (!fs.existsSync(DATA_FILE)) {
            console.log("No data file exists yet to send report.");
            return;
        }

        const dataStr = fs.readFileSync(DATA_FILE, 'utf8');
        const db = JSON.parse(dataStr);

        const emails = db.settings?.emails;
        if (!emails) {
            console.log("No recipient emails configured.");
            return;
        }

        // Calculate today's stats
        const todayStr = new Date().toISOString().slice(0, 10);
        let todaySales = 0;
        let todayStockIn = 0;
        let salesHtml = '';

        const txs = db.transactions || [];
        const products = db.products || [];

        const todaysTxs = txs.filter(t => t.date === todayStr);

        todaysTxs.forEach(t => {
            const p = products.find(prod => prod.id === t.productId);
            const pName = p ? `${p.name} (${p.color}/${p.size})` : 'Unknown';
            if (t.type === 'OUT') {
                todaySales += t.total;
                salesHtml += `<tr>
                    <td style="padding: 8px; border: 1px solid #ddd;">${t.entityName}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${pName}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${t.qty}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">₹${t.total}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${t.paymentMode || 'Cash'}</td>
                </tr>`;
            } else if (t.type === 'IN') {
                todayStockIn += t.qty;
            }
        });

        if (salesHtml === '') {
            salesHtml = '<tr><td colspan="5" style="text-align:center; padding: 10px;">No sales recorded today.</td></tr>';
        }

        const emailContent = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
            <h2 style="color: #d63031; text-align: center; border-bottom: 2px solid #d63031; padding-bottom: 10px;">BAZRIO.COM - Daily Summary</h2>
            <p style="text-align: right; color: #777;">Date: ${todayStr}</p>

            <div style="background: #f1f2f6; padding: 15px; border-radius: 5px; margin-bottom: 20px;">
                <h3 style="margin-top: 0;">Today's Overview</h3>
                <ul style="list-style: none; padding: 0;">
                    <li><strong>Total Sales Value:</strong> ₹${todaySales}</li>
                    <li><strong>Total Stock Items Added:</strong> ${todayStockIn}</li>
                </ul>
            </div>

            <h3>Today's Sales Breakdown</h3>
            <table style="width: 100%; border-collapse: collapse; text-align: left;">
                <thead style="background: #333; color: white;">
                    <tr>
                        <th style="padding: 10px;">Entity</th>
                        <th style="padding: 10px;">Product</th>
                        <th style="padding: 10px;">Qty</th>
                        <th style="padding: 10px;">Total</th>
                        <th style="padding: 10px;">Payment</th>
                    </tr>
                </thead>
                <tbody>
                    ${salesHtml}
                </tbody>
            </table>

            <p style="text-align: center; font-size: 12px; color: #aaa; margin-top: 30px;">
                Automated email generated by Bazrio Stock Manager System.
            </p>
        </div>
        `;

        await transporter.sendMail({
            from: '"BAZRIO System" <admin@eyecamp.digital>',
            to: emails,
            subject: `BAZRIO Daily Stock & Sales Report - ${todayStr}`,
            html: emailContent
        });
        console.log(`Daily report sent successfully to ${emails}`);

    } catch (err) {
        console.error("Failed to send daily report email:", err);
    }
}

// Schedule cron job to run at 8:00 PM (20:00) every day
cron.schedule('0 20 * * *', () => {
    console.log('Running daily email cron job...');
    sendDailyReport();
});

// Server
const server = http.createServer((req, res) => {
  const parsedUrl = url.parse(req.url);

  // Handle POST /sync to save data from localStorage
  if (req.method === 'POST' && parsedUrl.pathname === '/sync') {
      const authHeader = req.headers['authorization'];
      if (authHeader !== 'Bearer Chandna988@@@') {
          res.writeHead(401);
          res.end('Unauthorized');
          return;
      }

      let body = '';
      req.on('data', chunk => {
          body += chunk.toString();
      });
      req.on('end', () => {
          try {
              // Basic validation that it's JSON
              JSON.parse(body);
              fs.writeFile(DATA_FILE, body, 'utf8', (err) => {
                  if (err) {
                      console.error("Error writing data.json:", err);
                      res.writeHead(500);
                      res.end('Internal Server Error');
                      return;
                  }
                  res.writeHead(200, { 'Content-Type': 'application/json' });
                  res.end(JSON.stringify({ status: 'ok' }));
              });
          } catch (e) {
              res.writeHead(400);
              res.end('Invalid JSON');
          }
      });
      return;
  }

  // Sanitize path to prevent directory traversal
  let sanitizePath = path.normalize(parsedUrl.pathname).replace(/^(\.\.[\/\\])+/, '');

  if (sanitizePath === '/' || sanitizePath === '\\') {
      sanitizePath = '/index.html';
  }

  // Resolve absolute path and ensure it's still within __dirname
  let filePath = path.join(__dirname, sanitizePath);

  if (!filePath.startsWith(__dirname)) {
      res.writeHead(403);
      res.end('Forbidden');
      return;
  }

  // Explicitly deny access to backend files
  const forbiddenFiles = ['.env', 'data.json', 'index.js', 'package.json', 'package-lock.json', '.gitignore'];
  const baseName = path.basename(filePath);
  if (forbiddenFiles.includes(baseName) || sanitizePath.startsWith('/node_modules')) {
      res.writeHead(403);
      res.end('Forbidden');
      return;
  }

  let extname = path.extname(filePath);
  let contentType = 'text/html';

  switch (extname) {
    case '.js':
      contentType = 'text/javascript';
      break;
    case '.css':
      contentType = 'text/css';
      break;
    case '.json':
      contentType = 'application/json';
      break;
    case '.png':
      contentType = 'image/png';
      break;
    case '.jpg':
      contentType = 'image/jpg';
      break;
  }

  fs.readFile(filePath, (err, content) => {
    if (err) {
      if(err.code == 'ENOENT'){
        res.writeHead(404);
        res.end('Not Found');
      } else {
        res.writeHead(500);
        res.end('Server Error');
      }
    } else {
      res.writeHead(200, { 'Content-Type': contentType });
      res.end(content, 'utf-8');
    }
  });
});

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});
